export type Lang = "zh" | "en";
export type Cat = "all" | "home" | "campaign" | "list" | "detail" | "main" | "brand" | "service" | "scene";

export type WorkItem = {
  id: string;
  img: string;
  poster?: string;
  cat: Exclude<Cat, "all">;
  ratio?: string;
  title: Record<Lang, string>;
  sub: Record<Lang, string>;
};

export const EMAIL = "q18617420447@163.com";
export const PHONE = "16632905663";

export const masters = [
  { img: "/media/masters/glaser.jpg", zh: "米尔顿·格拉泽", en: "Milton Glaser" },
  { img: "/media/masters/sag.jpg", zh: "斯特凡·萨格迈斯特", en: "Stefan Sagmeister" },
  { img: "/media/masters/kan.jpg", zh: "靳埭强", en: "Kan Tai-keung" },
  { img: "/media/masters/rams.jpg", zh: "迪特·拉姆斯", en: "Dieter Rams" },
  { img: "/media/masters/chan.jpg", zh: "陈幼坚", en: "Alan Chan" },
  { img: "/media/masters/rand.jpg", zh: "保罗·兰德", en: "Paul Rand" },
  { img: "/media/masters/wuyong.jpg", zh: "吴勇", en: "Wu Yong" },
  { img: "/media/masters/hara.jpg", zh: "原研哉", en: "Kenya Hara" },
  { img: "/media/masters/ive.jpg", zh: "乔纳森·伊夫", en: "Jony Ive" },
  { img: "/media/masters/scher.jpg", zh: "宝拉·谢尔", en: "Paula Scher" },
];

export const tools = ["Photoshop", "Illustrator", "Premiere", "After Effects", "剪映", "DaVinci", "Figma", "WordPress", "ComfyUI", "Hunyuan", "MiniMax"];

export const skills = [
  { zh: "Photoshop", en: "Photoshop", width: "92%" },
  { zh: "Illustrator", en: "Illustrator", width: "80%" },
  { zh: "Premiere", en: "Premiere", width: "76%" },
  { zh: "After Effects", en: "After Effects", width: "70%" },
  { zh: "剪映", en: "CapCut", width: "84%" },
  { zh: "DaVinci", en: "DaVinci", width: "64%" },
  { zh: "Figma", en: "Figma", width: "72%" },
];

export const photos: WorkItem[] = [
  {
    id: "photo-flag",
    img: "/media/photo/flag.jpg",
    cat: "scene",
    title: { zh: "钟楼", en: "The clock tower" },
    sub: { zh: "旗杆对着蓝天", en: "Flag against the sky" },
  },
  {
    id: "photo-telecom",
    img: "/media/photo/telecom.jpg",
    cat: "scene",
    title: { zh: "电讯大楼", en: "The telecom block" },
    sub: { zh: "金字还在墙上", en: "The gold letters are still up" },
  },
  {
    id: "photo-trees",
    img: "/media/photo/trees.jpg",
    cat: "scene",
    title: { zh: "树后", en: "Behind the trees" },
    sub: { zh: "钟面只露出一半", en: "Half a clock through the leaves" },
  },
  {
    id: "photo-rust",
    img: "/media/photo/rust.jpg",
    cat: "scene",
    title: { zh: "红墙", en: "Red wall" },
    sub: { zh: "旧楼贴着新玻璃", en: "Old brick against new glass" },
  },
  {
    id: "photo-plant",
    img: "/media/photo/plant.jpg",
    cat: "scene",
    title: { zh: "厂区", en: "The plant" },
    sub: { zh: "冷却塔冒着烟", en: "Cooling towers in the haze" },
  },
  {
    id: "photo-rail",
    img: "/media/photo/rail.jpg",
    cat: "scene",
    title: { zh: "铁路", en: "The yard" },
    sub: { zh: "股道对着冷却塔", en: "Tracks toward the towers" },
  },
  {
    id: "photo-cat",
    img: "/media/photo/cat.jpg",
    cat: "scene",
    title: { zh: "台阶上", en: "On the steps" },
    sub: { zh: "一只躺着的猫", en: "A cat lying down" },
  },
];

export const works: WorkItem[] = [
  {
    id: "pollen",
    img: "/media/work/pollen.jpg",
    poster: "/media/posters/pollen-hero.jpg",
    ratio: "900 / 1400",
    cat: "detail",
    title: { zh: "茶花粉", en: "Camellia pollen" },
    sub: { zh: "食品详情页", en: "Food detail page" },
  },
  {
    id: "pear-light",
    img: "/media/work/pear-light.jpg",
    poster: "/media/posters/pearL-hero.jpg",
    ratio: "3 / 5",
    cat: "detail",
    title: { zh: "百草梨膏糖", en: "Pear lozenge" },
    sub: { zh: "商品详情页", en: "Product detail page" },
  },
  {
    id: "dog",
    img: "/media/work/dogfood.jpg",
    poster: "/media/posters/dog-hero.jpg",
    ratio: "790 / 1200",
    cat: "detail",
    title: { zh: "鱼油夹心犬粮", en: "Fish-oil dog food" },
    sub: { zh: "宠物详情页", en: "Pet detail page" },
  },
  {
    id: "pear-hand",
    img: "/media/work/pear-light.jpg",
    poster: "/media/posters/pearL-hand.jpg",
    ratio: "900 / 1300",
    cat: "detail",
    title: { zh: "百草梨膏糖 · 手工敲打", en: "Lozenge, broken by hand" },
    sub: { zh: "同一详情的下一屏", en: "Next screen of the same page" },
  },
];

export const jobs = [
  {
    when: { zh: "2024.03 – 至今", en: "2024.03 – Present" },
    role: { zh: "视觉设计", en: "Visual design" },
    org: { zh: "邢台玩家定制商贸有限公司", en: "Xingtai Wanjia Dingzhi Shangmao Youxian Gongsi" },
    img: "/media/work/pollen.jpg",
    points: {
      zh: [
        "负责电商店铺整体视觉：商品主图、详情页、活动页、营销推广图及店铺装修。",
        "完成视频号 / 短视频剪辑与基础包装。",
        "参与抖音直播间搭建及日常直播视觉支持。",
        "协助店铺视觉升级，公司整体销售额突破亿元级。",
      ],
      en: [
        "Owned store visuals: main images, detail pages, campaign pages, promo graphics, and shop decoration.",
        "Cut and packaged short videos for WeChat Channels.",
        "Built Douyin livestream sets and supported day-to-day live visuals.",
        "Helped upgrade the shop look. Company sales passed the 100-million-yuan level.",
      ],
    },
  },
  {
    when: { zh: "2022.03 – 2022.11", en: "2022.03 – 2022.11" },
    role: { zh: "视觉设计", en: "Visual design" },
    org: { zh: "北京同辉佳业科技有限公司", en: "Beijing Tonghui Jiaye Keji Youxian Gongsi" },
    img: "/media/work/pollen.jpg",
    points: {
      zh: [
        "负责京东 / 淘宝 / 天猫店铺视觉，ThinkPlus 等数码 3C 主图与活动素材。",
        "参与 618、双 11 大促页面、直通车图及多平台直播间视觉。",
      ],
      en: [
        "JD, Taobao, and Tmall visuals, including ThinkPlus and other 3C main images and campaign assets.",
        "618 and Double 11 pages, sponsored-search images, and livestream visuals.",
      ],
    },
  },
  {
    when: { zh: "2019.07 – 2022.01", en: "2019.07 – 2022.01" },
    role: { zh: "视觉设计", en: "Visual design" },
    org: { zh: "九阳保立时间科技有限公司", en: "Jiuyang Baoli Shijian Keji Youxian Gongsi" },
    img: "/media/work/pollen.jpg",
    points: {
      zh: [
        "负责日常电商视觉：主图、详情页、直通车、超级推荐及站外推广图。",
        "输出 618 / 双 11 / 双 12 活动页及 PC / 移动端店铺装修。",
      ],
      en: [
        "Daily shop visuals: main images, detail pages, sponsored ads, Super Recommendation, and off-site graphics.",
        "618, Double 11, and Double 12 campaign pages, plus PC and mobile shop decoration.",
      ],
    },
  },
] as const;

export const ui = {
  zh: {
    nav: [
      { href: "#work", label: "作品" },
      { href: "#photo", label: "摄影" },
      { href: "#ai", label: "生图" },
      { href: "#video", label: "视频" },
      { href: "#docs", label: "文稿" },
      { href: "#timeline", label: "经历" },
    ],
    menuFoot: ["河北 · 邢台", "电商视觉设计"],
    contact: "联系我",
    hero: ["少即是多"],
    heroSub: "主图、详情页、活动与直播",
    heroKeys: [
      "电商首页",
      "活动专题页",
      "商品列表页",
      "商品详情页",
      "商品主图",
      "营销落地页",
      "购物车页",
      "结算支付页",
      "订单确认页",
      "个人中心页",
      "会员权益页",
      "消息通知页",
      "帮助中心页",
      "品牌故事页",
      "售后物流页",
    ],
    heroCta: "看作品",
    ticker: "每天在用的工具",
    statement: [
      { t: "七年全平台电商视觉实战经验，", br: true },
      { t: "精通淘宝、天猫、京东、", br: true },
      { t: "抖音、拼多多", br: true },
      { t: "的流量逻辑与视觉玩法，", br: true },
      { t: "可独立承接主图优化、详情页升级、", br: true },
      { t: "大促活动视觉设计、店铺全套装修、", br: true },
      { t: "电商短视频制作、直播间视觉全案", br: true },
      { t: "六大类业务，全流程无需多方对接，", br: true },
      { t: "一站式交付符合平台转化要求的落地成果。" },
    ],
    aboutKicker: "关于我",
    eduKicker: "教育经历",
    eduWhen: "2015 – 2018",
    eduOrg: "山东现代学院",
    eduNote: "大专 · 视觉传达",
    jobKicker: "工作经历",
    scopeKicker: "能独立交付的四块",
    scopeTitle: ["主图、详情、", "活动，和直播"],
    scopeLink: "查看全部作品",
    stageKicker: "样机",
    stageTitle: "放进手机、平板、折叠屏和电脑",
    stagePreview: "预览",
    stagePrev: "上一页",
    stageNext: "下一页",
    stagePhone: "iPhone 18 Pro",
    stageTablet: "iPad Air",
    stageFold: "iPhone Duo",
    stageMac: "MacBook Pro",
    scopes: [
      { title: "主图", body: "商品先看清。角度、比例和卖点只保留画面里真实存在的。", img: "/media/work/dogfood.jpg" },
      { title: "详情页", body: "长图往下读：工艺、卖点、参数和食用方法，按顺序排开。", img: "/media/work/pollen.jpg" },
      { title: "活动页", body: "618、双 11、双 12 和店铺装修，PC 与移动端一起出。", img: "/media/work/pear-light.jpg" },
      { title: "短视频 / 直播", body: "视频号剪辑、基础包装，以及抖音直播间的日常视觉。", img: "/media/video/hy-05.jpg" },
    ],
    skillKicker: "专业技能",
    skillTitle: ["不只会软件", "会把一店的视觉做完"],
    skillNote: "熟练使用 Photoshop、Illustrator、Premiere、AE、剪映、DaVinci、Figma，并有 WordPress 独立站经验。条形只对照简历里的熟练程度，不另标分数。ComfyUI、混元和 MiniMax 是自己练的生图生视频，不写成客户项目。",
    workKicker: "作品",
    workTitle: ["作品展示"],
    photoKicker: "摄影",
    photoTitle: ["路上拍的"],
    photoNote: "建筑、厂区和一只猫。点开看全尺寸。",
    cats: [
      { id: "all" as Cat, label: "全部" },
      { id: "detail" as Cat, label: "商品详情页" },
    ],
    caseKicker: "选一页打开",
    caseTitle: ["长图可以", "整页看完"],
    footWorks: "作品",
    footContact: "联络",
    footPlace: "所在",
    copyMail: "复制邮箱",
    copied: "已复制",
    rights: "保留所有权利。",
    sheetKicker: "河北 · 邢台",
    sheetTitle: "有项目可以直接联系",
    sheetBody: "视觉设计师 Revo。主图、详情页、活动页、店铺装修、短视频和直播间视觉。",
    call: "打电话",
    mail: "发邮件",
    open: "查看",
    close: "关闭",
    zoom: "放大倍数",
    menuOpen: "打开菜单",
    menuClose: "关闭菜单",
  },
  en: {
    nav: [
      { href: "#work", label: "Work" },
      { href: "#photo", label: "Photos" },
      { href: "#ai", label: "AI" },
      { href: "#video", label: "Film" },
      { href: "#docs", label: "Notes" },
      { href: "#timeline", label: "Jobs" },
    ],
    menuFoot: ["Xingtai, Hebei", "E-commerce visual design"],
    contact: "Contact",
    hero: ["Less is more"],
    heroSub: "Listings, detail pages, campaigns, live",
    heroKeys: [
      "Store home",
      "Campaign page",
      "Listing page",
      "Product detail",
      "Hero image",
      "Landing page",
      "Cart",
      "Checkout",
      "Order confirmation",
      "Account",
      "Membership",
      "Notifications",
      "Help center",
      "Brand story",
      "Shipping & returns",
    ],
    heroCta: "See work",
    ticker: "Tools in daily use",
    statement: [
      { t: "Seven years across every major platform.", br: true },
      { t: "Taobao, Tmall, JD, Douyin,", br: true },
      { t: "Pinduoduo —", br: true },
      { t: "the traffic logic and the visual play.", br: true },
      { t: "Main images, detail pages, campaigns,", br: true },
      { t: "full shop decoration, short video,", br: true },
      { t: "and livestream visuals, taken alone.", br: true },
      { t: "One handoff. No extra vendors.", br: true },
      { t: "Delivered for what each platform converts." },
    ],
    aboutKicker: "About",
    eduKicker: "Education",
    eduWhen: "2015 – 2018",
    eduOrg: "Shandong Modern University",
    eduNote: "Associate · Visual communication",
    jobKicker: "Experience",
    scopeKicker: "Four things I ship alone",
    scopeTitle: ["Listings, pages,", "campaigns, and live."],
    scopeLink: "All work",
    stageKicker: "Devices",
    stageTitle: "Phone, tablet, foldable, and laptop.",
    stagePreview: "Preview",
    stagePrev: "Previous",
    stageNext: "Next",
    stagePhone: "iPhone 18 Pro",
    stageTablet: "iPad Air",
    stageFold: "iPhone Duo",
    stageMac: "MacBook Pro",
    scopes: [
      { title: "Main image", body: "The product has to read first. Angle and claim stay tied to what is actually in frame.", img: "/media/work/dogfood.jpg" },
      { title: "Detail page", body: "A long page in order: craft, benefits, specs, and how to use it.", img: "/media/work/pollen.jpg" },
      { title: "Campaign", body: "618, Double 11, Double 12, and shop decoration for both PC and mobile.", img: "/media/work/pear-light.jpg" },
      { title: "Short video / live", body: "Channel edits, basic packaging, and day-to-day Douyin livestream visuals.", img: "/media/video/hy-05.jpg" },
    ],
    skillKicker: "Skills",
    skillTitle: ["Not just the software.", "A whole shop's visuals, finished."],
    skillNote: "Photoshop, Illustrator, Premiere, After Effects, CapCut, DaVinci, and Figma, plus WordPress. Bars follow the resume. No made-up scores. ComfyUI, Hunyuan, and MiniMax are personal image and video studies, not client jobs.",
    workKicker: "Work",
    workTitle: ["Selected work"],
    photoKicker: "Photos",
    photoTitle: ["Shot on the way"],
    photoNote: "Buildings, a plant, and a cat. Open one to see it full size.",
    cats: [
      { id: "all" as Cat, label: "All" },
      { id: "detail" as Cat, label: "Detail page" },
    ],
    caseKicker: "Open a page",
    caseTitle: ["Long pages", "can be read through."],
    footWorks: "Work",
    footContact: "Contact",
    footPlace: "Based in",
    copyMail: "Copy email",
    copied: "Copied",
    rights: "All rights reserved.",
    sheetKicker: "Xingtai, Hebei",
    sheetTitle: "Write if there is a project.",
    sheetBody: "Revo Gong, visual designer. Main images, detail pages, campaigns, shop decoration, short video, and livestream visuals.",
    call: "Call",
    mail: "Email",
    open: "View",
    close: "Close",
    zoom: "Zoom",
    menuOpen: "Open menu",
    menuClose: "Close menu",
  },
} as const;
